version: '3.7'
services:
  agetest-service:
      container_name: agetest-service
      image: convenantgemeenten/agetest-service:latest
      restart: always
      ports:
        - '8080'
      environment:
        - "AGETEST_CONFIGS_PATH=/home/librarian/conf/"
      volumes:
        - ./config/agetest:/home/librarian/conf:ro
        - ./.data/agetest:/home/librarian/graph
      networks:
        - backend
  kinsmantest-service:
      container_name: kinsmantest-service
      image: convenantgemeenten/kinsmantest-service:latest
      restart: always
      ports:
        - '8080'
      environment:
        - "KINSMANTEST_CONFIGS_PATH=/home/librarian/conf/"
      volumes:
        - ./config/kinsmantest:/home/librarian/conf:ro
        - ./.data/kinsmantest:/home/librarian/graph
      networks:
        - backend
  guardianshiptest-service:
      container_name: guardianshiptest-service
      image: convenantgemeenten/guardianshiptest-service:latest
      restart: always
      ports:
        - '8080'
      environment:
        - "GUARDIANSHIPTEST_CONFIGS_PATH=/home/librarian/conf/"
      volumes:
        - ./config/guardianshiptest:/home/librarian/conf:ro
        - ./.data/guardianshiptest:/home/librarian/graph
      networks:
        - backend
  nginx:
    depends_on:
      - agetest-service
      - kinsmantest-service
      - guardianshiptest-service
    image: nginx:latest
    restart: always
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - frontend
      - backend

networks:
  frontend:
  backend:
